workflows:
  android-workflow:
    name: Chinese Novel Game Build
    max_build_duration: 30
    environment:
      java: 11
    scripts:
      - name: Build APK
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk